name: Deploy

on:
    push:
        branches:
            - main
jobs:
    cdk-deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            pull-requests: write
        steps:
            - name: AWS Athenticate
              uses: aws-actions/configure-aws-credentials@v1.6.1
              with:
                  role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/Github-Actions-Role-${{ secrets.AWS_ACCOUNT_NUMBER }}
                  aws-region: us-east-1
            - name: Checkout Source
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install AWS CDK
              run: |
                npm install -g aws-cdk
              shell: bash
            - name: CDK Build and Deploy
              run: |
                npm install
                cdk diff
                cdk deploy --require-approval never
              shell: bash
              working-directory: iac