name: Pull Request

on: [pull_request]

jobs:
  cdk-diff:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps: 
      - name: AWS Athenticate
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/Github-Actions-Role-${{ secrets.AWS_ACCOUNT_NUMBER }}
            aws-region: us-east-1
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: CDK Diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
          working_dir: iac
        env:
          AWS_DEFAULT_REGION: 'us-east-1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}